// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwcuxydolkkndgaucaki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3Y3V4eWRvbGtrbmRnYXVjYWtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDAyMzAsImV4cCI6MjA2NjI3NjIzMH0.u8Rhx5HFB3z7PViOxte2D9lOep0PI3xE-HFEIVcZ22I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);